name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build-push
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        echo 'Docker Login...'
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
        echo 'running build...'
        docker build . -t appsody-codewind-github-actions-nodejs:latest
        docker tag appsody-codewind-github-actions-nodejs:latest dewan2018/github-actions:latest
        echo 'Pushing image...'
        docker push dewan2018/github-actions:latest
        echo 'Done!'
      
